defaults: &defaults
  fitbit:
    consumer_key:    <%= ENV['FITBIT_CONSUMER_KEY']    || 'YOUR_CONSUMER_KEY'    %>
    consumer_secret: <%= ENV['FITBIT_CONSUMER_SECRET'] || 'YOUR_CONSUMER_SECRET' %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
